// <auto-generated />
using System;
using AmadeusHotels.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AmadeusHotels.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210430180151_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AmadeusHotels.Entities.Models.Hotel", b =>
                {
                    b.Property<string>("HotelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("HotelId");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("AmadeusHotels.Entities.Models.SearchRequest", b =>
                {
                    b.Property<int>("SearchRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Adults")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NextItemsLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidUntil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.HasKey("SearchRequestId");

                    b.HasIndex("CheckInDate");

                    b.HasIndex("CheckOutDate");

                    b.HasIndex("CityCode");

                    b.HasIndex("CityCode", "CheckInDate", "CheckOutDate");

                    b.ToTable("SearchRequest");
                });

            modelBuilder.Entity("AmadeusHotels.Entities.Models.SearchRequestHotel", b =>
                {
                    b.Property<int>("SearchRequestHotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<float?>("Distance")
                        .HasColumnType("real");

                    b.Property<string>("HotelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PriceCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("PriceTotal")
                        .HasColumnType("real");

                    b.Property<int>("SearchRequestId")
                        .HasColumnType("int");

                    b.HasKey("SearchRequestHotelId");

                    b.HasIndex("HotelId");

                    b.HasIndex("SearchRequestId");

                    b.ToTable("SearchRequestHotel");
                });

            modelBuilder.Entity("AmadeusHotels.Entities.Models.SearchRequestHotel", b =>
                {
                    b.HasOne("AmadeusHotels.Entities.Models.Hotel", "Hotel")
                        .WithMany("SearchRequestHotels")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmadeusHotels.Entities.Models.SearchRequest", "SearchRequest")
                        .WithMany("SearchRequestHotels")
                        .HasForeignKey("SearchRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("SearchRequest");
                });

            modelBuilder.Entity("AmadeusHotels.Entities.Models.Hotel", b =>
                {
                    b.Navigation("SearchRequestHotels");
                });

            modelBuilder.Entity("AmadeusHotels.Entities.Models.SearchRequest", b =>
                {
                    b.Navigation("SearchRequestHotels");
                });
#pragma warning restore 612, 618
        }
    }
}
